# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMSH-Summer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMSH-Summer
  pod 'SnapKit', '~> 5.0.0'
  pod 'RealmSwift', '~>10'
  pod 'Kingfisher', '~> 7.0'
  pod 'NMapsMap','3.15.0'
end
